### ISSUE TITLE
NOAA 'Omics Technical Portal Tags

### ISSUE THREAD

**Issue by marinednadude** [McAllister-NOAA/REVAMP#1]
Hi Sean,

As a part of the [NOAA 'Omics Technical Portal](https://noaa-omics-technical-portal.readthedocs.io/en/latest/index.html) we are trying to add relevant tags to different NOAA 'Omics related software on Github. Would you be able to the following tags to your NOAA 'Omics repositories so we can link and search them effectively: noaa-omics-software.

Thanks for your help!

Best,

Zack

**Comment by McAllister-NOAA** [comment]
No problem. Added!
